package org.oncoblocks.data_block.model;

/**
 * Constants for the Oncotator Annotations.
 */
public class OncotatorAnnotations {
    public static final String ONCOTATOR_GENE_SYMBOL  = "ONCOTATOR_GENE_SYMBOL";
    public static final String ONCOTATOR_VARIANT_CLASSIFICATION  = "ONCOTATOR_VARIANT_CLASSIFICATION";
    public static final String ONCOTATOR_PROTEIN_CHANGE = "ONCOTATOR_PROTEIN_CHANGE";
    public static final String ONCOTATOR_COSMIC_OVERLAPPING = "ONCOTATOR_COSMIC_OVERLAPPING";
    public static final String ONCOTATOR_DBSNP_RS = "ONCOTATOR_DBSNP_RS";
    public static final String ONCOTATOR_UNIPROT_ACCESSION = "ONCOTATOR_UNIPROT_ACCESSION";
    public static final String ONCOTATOR_UNIPROT_ENTRYNAME = "ONCOTATOR_UNIPROT_ENTRYNAME";
    public static final String ONCOTATOR_UNIPROT_PROTEIN_POSITION_START = "ONCOTATOR_UNIPROT_PROTEIN_POSITION_START";
    public static final String ONCOTATOR_UNIPROT_PROTEIN_POSITION_END = "ONCOTATOR_UNIPROT_PROTEIN_POSITION_END";
    public static final String ONCOTATOR_REFERENCE_PROTEIN_ALLELE = "ONCOTATOR_REFERENCE_PROTEIN_ALLELE";
    public static final String ONCOTATOR_OBSERVED_PROTEIN_ALLELE = "ONCOTATOR_OBSERVED_PROTEIN_ALLELE";
    public static final String ONCOTATOR_REF_SEQ_MRNA_ID = "ONCOTATOR_REF_SEQ_MRNA_ID";
    public static final String ONCOTATOR_REF_SEQ_PROTEIN_ID = "ONCOTATOR_REF_SEQ_PROTEIN_ID";
}